// <auto-generated />
using System;
using Cw7.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cw7.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cw7.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "0000000000",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "Description0",
                            Name = "Component0"
                        },
                        new
                        {
                            Code = "0000000001",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 2,
                            Description = "Description1",
                            Name = "Component1"
                        },
                        new
                        {
                            Code = "0000000002",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 2,
                            Description = "Description2",
                            Name = "Component2"
                        });
                });

            modelBuilder.Entity("Cw7.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abrreviation = "cos1",
                            FoundationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Dell"
                        },
                        new
                        {
                            Id = 2,
                            Abrreviation = "cos2",
                            FoundationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Dell1"
                        },
                        new
                        {
                            Id = 3,
                            Abrreviation = "cos2",
                            FoundationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Dell2"
                        });
                });

            modelBuilder.Entity("Cw7.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CT",
                            Name = "ComponentType1"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "CT1",
                            Name = "ComponentType2"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "CT",
                            Name = "ComponentType3"
                        });
                });

            modelBuilder.Entity("Cw7.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC1",
                            Stock = 20,
                            Warranty = 2,
                            Weight = 5.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC2",
                            Stock = 10,
                            Warranty = 3,
                            Weight = 2.5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PC3",
                            Stock = 3,
                            Warranty = 1,
                            Weight = 8.5
                        });
                });

            modelBuilder.Entity("Cw7.Models.PCcomponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000000",
                            Amount = 10
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "0000000001",
                            Amount = 30
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "0000000002",
                            Amount = 20
                        });
                });

            modelBuilder.Entity("Cw7.Models.Component", b =>
                {
                    b.HasOne("Cw7.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany()
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cw7.Models.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Cw7.Models.PCcomponent", b =>
                {
                    b.HasOne("Cw7.Models.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cw7.Models.PC", "PC")
                        .WithMany("PCcomponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("Cw7.Models.PC", b =>
                {
                    b.Navigation("PCcomponents");
                });
#pragma warning restore 612, 618
        }
    }
}
